FROM docker.io/cachyos/cachyos-v3:latest

ARG BASE_OPT_TIMEZONE
ARG BASE_OPT_KEYMAP
ARG BASE_OPT_LANGUAGE

RUN pacman-key --init && pacman-key --populate archlinux cachyos && \
    pacman --noconfirm -Syy && \
    ln -sf /usr/share/zoneinfo/${BASE_OPT_TIMEZONE} /etc/localtime && \
    echo "KEYMAP=${BASE_OPT_KEYMAP}" > /etc/vconsole.conf && \
    echo "LANG=${BASE_OPT_LANGUAGE}.UTF-8" > /etc/locale.conf && \
    echo "${BASE_OPT_LANGUAGE}.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen && \
    mkdir -p /etc/mkinitcpio.conf.d && \
    echo "HOOKS=(base systemd ostree autodetect modconf kms keyboard sd-vconsole block filesystems fsck)" \
        > /etc/mkinitcpio.conf.d/ostree.conf && \
    echo "options overlay metacopy=off redirect_dir=off" \
        > /etc/modprobe.d/disable-overlay-redirect-dir.conf && \
    echo "blacklist nouveau" > /etc/modprobe.d/blacklist-nouveau.conf && \
    pacman --noconfirm --needed -S polkit networkmanager && \
    systemctl enable NetworkManager.service && \
    systemctl enable systemd-resolved.service && \
    systemctl mask systemd-networkd-wait-online.service && \
    pacman --noconfirm --needed -Syuu \
        linux-cachyos linux-cachyos-headers linux-firmware \
        sof-firmware alsa-firmware alsa-ucm-conf \
        amd-ucode intel-ucode \
        dosfstools xfsprogs \
        grub mkinitcpio efibootmgr \
        ostree skopeo podman which \
        nano vim git wget curl htop jq sbctl \
        man-db man-pages bash-completion \
        usbutils pciutils inetutils bolt \
        openssh rsync zip unzip p7zip \
        exfatprogs btrfs-progs udisks2

RUN moduledir=$(find /usr/lib/modules -mindepth 1 -maxdepth 1 -type d) && \
    kernel=$(cat ${moduledir}/pkgbase) && \
    cat /boot/*-ucode.img /boot/initramfs-${kernel}.img > ${moduledir}/initramfs.img
